baseURL = 'https://danielmcfarland.dev/'
languageCode = 'en-gb'
title = 'Daniel McFarland'
theme = 'typo'

[permalinks]
data = "/data/:slug/"

[taxonomies]
type = "type"

[params]
paginationSize = 100
#homeIntroTitle = 'Hi!'

homeIntroContent = """
Hi, I'm Daniel McFarland, and I'm a Senior Software Engineer at Scaffold Digital.

I may use this site as a method of sharing things I've learned or find interesting. My interests include Technology ğŸ‘¨ğŸ¼â€ğŸ’»â€, Coffee â˜•ï¸ and Running ğŸƒğŸ¼â€â™‚ï¸

Feel free to reach out and contact me at <a href="mailto:hi@danielmcfarland.dev">hi@danielmcfarland.dev</a> or at any of the social links below.
"""

[[params.menu]]
name = "home"
url = "/"

#[[params.menu]]
#name = "about"
#url = "/about"

#[[params.menu]]
#name = "posts"
#url = "/posts"

[[params.menu]]
name = "bookmarks"
url = "/type/bookmarks"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/daniel.a.mcfarland/"

[[params.social]]
name = "mastodon"
url = "https://mastodon.social/@danielmcfarland/"

[[params.social]]
name = "github"
url = "https://github.com/danielmcfarland/"

[[params.social]]
name = "strava"
url = "https://www.strava.com/athletes/69023309/"

[[params.social]]
name = "twitter"
url = "https://twitter.com/daniel.mcf/"