baseURL = 'https://danielmcfarland.dev/'
languageCode = 'en-gb'
title = 'Daniel McFarland'
theme = 'typo'

[params]
#homeIntroTitle = 'Hi!'

homeIntroContent = """
Senior Developer ğŸ‘¨ğŸ¼â€ğŸ’» Running ğŸƒğŸ¼â€â™‚ï¸ Coffee â˜•ï¸
"""

[[params.menu]]
name = "home"
url = "/"

#[[params.menu]]
#name = "about"
#url = "/about"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/daniel.a.mcfarland/"

[[params.social]]
name = "mastodon"
url = "https://mastodon.social/@danielmcfarland/"

[[params.social]]
name = "github"
url = "https://github.com/danielmcfarland/"